# -*- coding: utf-8 -*-
"""Übung while Schleife.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dwg8QKPxFbQijwuNSsBTEFigosDrpEEK

SPD = 25.7
CDU_CSU = 24.1
Gruene = 14.8
FDP = 11.5
AfD = 10.3
Linke = 4.9
"""

SPD = 25.7
CDU_CSU = 24.1
Gruene = 14.8
FDP = 11.5
AfD = 10.3
Linke = 4.9

Mehrheit = 0

while Mehrheit < 50.1:

  Eingabe = input("Geben Sie eine Partei ein. (SPD, CDU_CSU, Gruene, FDP, AfD, Linke)")

  if Eingabe == "SPD":
    Mehrheit = Mehrheit + SPD
    if Mehrheit < 50.1:
      print("Sie liegen bei", Mehrheit, "%", "Es ist noch keine Mehrheit gegeben")
    else:
      print("Eine Mehrheit von", Mehrheit, "% ist gegeben!")
  elif Eingabe == "CDU_CSU":
    Mehrheit = Mehrheit + CDU_CSU
    if Mehrheit < 50.1:
      print("Sie liegen bei", Mehrheit, "%", "Es ist noch keine Mehrheit gegeben")
    else:
      print("Eine Mehrheit von", Mehrheit, "% ist gegeben!")
  elif Eingabe == "Gruene":
    Mehrheit = Mehrheit + Gruene
    if Mehrheit < 50.1:
      print("Sie liegen bei", Mehrheit, "%", "Es ist noch keine Mehrheit gegeben")
    else:
      print("Eine Mehrheit von", Mehrheit, "% ist gegeben!")
  elif Eingabe == "FDP":
    Mehrheit = Mehrheit + FDP
    if Mehrheit < 50.1:
      print("Sie liegen bei", Mehrheit, "%", "Es ist noch keine Mehrheit gegeben")
    else:
      print("Eine Mehrheit von", Mehrheit, "% ist gegeben!")
  elif Eingabe == "AfD":
    Mehrheit = Mehrheit + AfD
    if Mehrheit < 50.1:
      print("Sie liegen bei", Mehrheit, "%", "Es ist noch keine Mehrheit gegeben")
    else:
      print("Eine Mehrheit von", Mehrheit, "% ist gegeben!")
  elif Eingabe == "Linke":
    Mehrheit = Mehrheit + Linke
    if Mehrheit < 50.1:
      print("Sie liegen bei", Mehrheit, "%", "Es ist noch keine Mehrheit gegeben")
    else:
      print("Eine Mehrheit von", Mehrheit, "% ist gegeben!")
  else:
    print("Diese Partei ist leider nicht dabei:", Eingabe)

"""# Übung Black Jack

*   Als Spieler erhalten Sie zwei Karten vom Computer (Croupier).
*   Alle Karten haben Werte zwischen 2 und 11. Jede Karte kommt gleich häufig vor.

Nach den zwei Karten hat der Spieler folgende Möglichkeiten:

hit: er zieht eine weitere Karte aus dem Stapel. Der Wert der Karte wird zu seinem Deck addiert.

stand: der Spieler hält seinen Deckwert und zieht keine weitere Karte.

surrender: der Spieler gibt auf und das Spiel ist beendet.

Kommt der Spieler über 21, hat er verloren
"""

import random
random.seed ()
Ergebnis = 0
Ergebnisbank = 0

#Einsatz festlegen
Einsatz = input("Wie viel Euro möchten Sie wetten?")
Einsatz = int(Einsatz)

#Spieleraktion festlegen
while Ergebnis <= 21:
  Karte = random.randint (2,11)
  Aktion = input("was wollen sie tun?")
  if Aktion == "hit" or Aktion == "Hit":  
    #Ass bewerten  
    if Karte == 11:
      Ass=input("Soll die Karte als 1 oder als 11 gewertet werden?")
      if Ass == "1":
        Karte = 1
      elif Ass == "11":
        Karte = 11
    Ergebnis = Ergebnis + Karte
    print(Ergebnis)
  #Ergebnis >21
  if Ergebnis > 21:
    print("Sie haben verloren!")
    Ergebnisbank = 50
    Einsatz = Einsatz - Einsatz
    break
  #Black Jack  
  if Ergebnis == 21:
    print("Sie haben Black Jack")
    Ergebnisbank = 50
    Einsatz = Einsatz * 3
    break
  #stand
  elif Aktion == "stand":
    print("Ihr Ergebnis lautet", Ergebnis)
    break
  #surrender
  elif Aktion == "surrender":
    print("Sie haben verloren!")
    Einsatz = Einsatz - Einsatz
    Ergebnisbank = 50
    break
  
#Bank
while Ergebnisbank < Ergebnis:
  Kartebank = random.randint (2,11)
  Ergebnisbank = Ergebnisbank + Kartebank
  print("Die Bank hat eine", Kartebank,"gezogen")
  #Bank < Spieler
  if Ergebnisbank < Ergebnis and Ergebnisbank <21:
    print("Die Bank liegt bei",Ergebnisbank, "und zieht eine weitere Karte")
  #Bank >21
  elif Ergebnisbank > 21:
    print("Die Bank liegt bei",Ergebnisbank, "Sie haben gewonnen!")
    Einsatz = Einsatz * 2
  #Bank gewinnt
  elif Ergebnisbank > Ergebnis and Ergebnisbank <= 21:
    print(Ergebnisbank, "Die Bank hat gewonnen")
    Einsatz = Einsatz - Einsatz
  #Unentschieden
  elif Ergebnisbank == Ergebnis:
    print("Unentschieden")

print("Ihr Guthaben liegt bei", Einsatz,"Euro")